"""empty message

Revision ID: 005a9bdd25dc
Revises: c86eccb51d23
Create Date: 2020-06-15 15:24:22.161156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005a9bdd25dc'
down_revision = 'c86eccb51d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_dnslookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_target', sa.Integer(), nullable=True),
    sa.Column('has_scanned', sa.Boolean(), nullable=True),
    sa.Column('dnslookup_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_target'], ['tb_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_dnslookup')
    # ### end Alembic commands ###
