"""empty message

Revision ID: 14f15cac4cca
Revises: ee93e8ac47e5
Create Date: 2020-06-10 01:40:23.430087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f15cac4cca'
down_revision = 'ee93e8ac47e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('last_status', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_target', 'last_status')
    # ### end Alembic commands ###
