"""empty message

Revision ID: 1d2194001748
Revises: 796fdb477a3f
Create Date: 2020-06-10 09:04:32.076586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d2194001748'
down_revision = '796fdb477a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status_code', sa.String(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status', mysql.VARCHAR(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status_code')
    # ### end Alembic commands ###
