"""empty message

Revision ID: 36f00eeb68fa
Revises: 3ddae1ef3345
Create Date: 2020-06-11 00:34:18.691076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36f00eeb68fa'
down_revision = '3ddae1ef3345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_revip', sa.Column('list_domain', mysql.JSON(), nullable=True))
    op.drop_column('tb_revip', 'domains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_revip', sa.Column('domains', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tb_revip', 'list_domain')
    # ### end Alembic commands ###
