"""empty message

Revision ID: 3a369785381d
Revises: 
Create Date: 2020-06-09 10:36:13.091735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a369785381d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', mysql.TINYTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('real_name', sa.String(length=40), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('pass_word', sa.String(length=63), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_name'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    op.drop_table('tb_target')
    op.drop_table('tb_role')
    # ### end Alembic commands ###
