"""empty message

Revision ID: 3d4bcec88d8f
Revises: 1fa351a62074
Create Date: 2020-06-11 12:44:17.469952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d4bcec88d8f'
down_revision = '1fa351a62074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status_code', sa.String(length=4), nullable=True))
    op.drop_column('tb_target', 'target_status_cod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status_cod', mysql.VARCHAR(length=4), nullable=True))
    op.drop_column('tb_target', 'target_status_code')
    # ### end Alembic commands ###
