"""empty message

Revision ID: 3ddae1ef3345
Revises: 0915c7b3c82a
Create Date: 2020-06-11 00:25:38.750763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddae1ef3345'
down_revision = '0915c7b3c82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_revip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_target', sa.Integer(), nullable=True),
    sa.Column('domains', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_target'], ['tb_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_revip')
    # ### end Alembic commands ###
