"""empty message

Revision ID: 5390e6bd1301
Revises: f4e03b3cdfab
Create Date: 2020-06-10 08:54:57.400817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5390e6bd1301'
down_revision = 'f4e03b3cdfab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_target', 'tb_user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_target', type_='foreignkey')
    op.drop_column('tb_target', 'id_user')
    # ### end Alembic commands ###
