"""empty message

Revision ID: 5d89b40fc256
Revises: 005a9bdd25dc
Create Date: 2020-06-17 17:44:25.306203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d89b40fc256'
down_revision = '005a9bdd25dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_whois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_target', sa.Integer(), nullable=True),
    sa.Column('has_scanned', sa.Boolean(), nullable=True),
    sa.Column('whois_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_target'], ['tb_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_whois')
    # ### end Alembic commands ###
