"""empty message

Revision ID: 773d1f37c047
Revises: 1d2194001748
Create Date: 2020-06-10 19:28:07.787451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '773d1f37c047'
down_revision = '1d2194001748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_country', sa.String(length=50), nullable=True))
    op.add_column('tb_target', sa.Column('target_server', sa.String(length=50), nullable=True))
    op.drop_column('tb_target', 'target_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_comment', mysql.TEXT(), nullable=True))
    op.drop_column('tb_target', 'target_server')
    op.drop_column('tb_target', 'target_country')
    # ### end Alembic commands ###
