"""empty message

Revision ID: 796fdb477a3f
Revises: 5390e6bd1301
Create Date: 2020-06-10 09:04:02.204798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '796fdb477a3f'
down_revision = '5390e6bd1301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status', sa.String(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status_code', mysql.VARCHAR(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status')
    # ### end Alembic commands ###
