"""empty message

Revision ID: a35702a99515
Revises: 14f15cac4cca
Create Date: 2020-06-10 01:48:25.048646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a35702a99515'
down_revision = '14f15cac4cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_comment', sa.Text(), nullable=True))
    op.add_column('tb_target', sa.Column('target_status', sa.String(length=3), nullable=True))
    op.add_column('tb_target', sa.Column('target_url', sa.String(length=50), nullable=False))
    op.drop_column('tb_target', 'url')
    op.drop_column('tb_target', 'last_status')
    op.drop_column('tb_target', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('comment', mysql.TEXT(), nullable=True))
    op.add_column('tb_target', sa.Column('last_status', mysql.VARCHAR(length=3), nullable=True))
    op.add_column('tb_target', sa.Column('url', mysql.TINYTEXT(), nullable=False))
    op.drop_column('tb_target', 'target_url')
    op.drop_column('tb_target', 'target_status')
    op.drop_column('tb_target', 'target_comment')
    # ### end Alembic commands ###
