"""empty message

Revision ID: b4eba20b659c
Revises: 
Create Date: 2020-06-13 01:57:35.080339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4eba20b659c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('real_name', sa.String(length=40), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('pass_word', sa.String(length=63), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_name'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('tb_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('target_url', sa.String(length=50), nullable=False),
    sa.Column('target_server', sa.String(length=20), nullable=True),
    sa.Column('target_country', sa.String(length=7), nullable=True),
    sa.Column('target_status_code', sa.String(length=4), nullable=True),
    sa.Column('submited_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_revip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_target', sa.Integer(), nullable=True),
    sa.Column('list_domain', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_target'], ['tb_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_revip')
    op.drop_table('tb_target')
    op.drop_table('tb_user')
    op.drop_table('tb_role')
    # ### end Alembic commands ###
