"""empty message

Revision ID: ee93e8ac47e5
Revises: 3a369785381d
Create Date: 2020-06-10 01:25:22.563931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee93e8ac47e5'
down_revision = '3a369785381d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('tb_target', sa.Column('submited_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_target', 'submited_at')
    op.drop_column('tb_target', 'comment')
    # ### end Alembic commands ###
