"""empty message

Revision ID: f4e03b3cdfab
Revises: a35702a99515
Create Date: 2020-06-10 02:13:50.095819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4e03b3cdfab'
down_revision = 'a35702a99515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status_code', sa.String(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_target', sa.Column('target_status', mysql.VARCHAR(length=3), nullable=True))
    op.drop_column('tb_target', 'target_status_code')
    # ### end Alembic commands ###
